{% set name = "DataProperty" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 723e5729fa6e885e127a771a983ee1e0e34bb141aca4ffe1f0bfa7cde34650a4

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.3.0
  run:
    - mbstrdecoder >=1.0.0
    - python >={{ python_min }}
    - setuptools >=38.3.0
    - typepy >=1.1.1

test:
  imports:
    - dataproperty
    - dataproperty.logger
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thombashi/DataProperty
  summary: Python library for extract property from data.
  dev_url: https://github.com/thombashi/DataProperty
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
