{% set name = "dataproperty" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dataproperty-{{ version }}.tar.gz
  sha256: b038437a4097d1a1c497695c3586ea34bea67fdd35372b9a50f30bf044d77d04

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=64
    - setuptools-scm >=8
    - releasecmd
    - pip
  run:
    - python >={{ python_min }}
    - mbstrdecoder >=1.0.0,<2
    - setuptools >=64
    - typepy >=1.3.2,<2

test:
  imports:
    - dataproperty
    - dataproperty.logger
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/thombashi/DataProperty
  summary: Python library for extract property from data.
  dev_url: https://github.com/thombashi/DataProperty
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - basnijholt
